### ISSUE TITLE
Display caching progress

### ISSUE THREAD

**Issue by sCreami** [torque/mpv-progressbar#18]
I'm using almost exclusively mpv to play files on network storages and I'd like to see the caching progress along with the playback progress.
Is it possible to add an overlay on the progress bar like the youtube player does ? (or as vlc)

**Comment by torque** [comment]
I'd also like a cache-progress overlay. I implemented one locally a few months back but the problem is that it isn't accurate. mpv does not easily expose the amount of cached video to the user. As far as I can tell, one should be able to compute it from the properties `cache-used` and `demuxer-cache-time`. That said, I haven't figured out the correct formula.

It's something I'll have to play around with more.
