### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by underr** [torque/mpv-progressbar#19]
With mpv-progressbar enabled the RAM usage of mpv playing a 720p video increases 2MB/s until it stops on the ~200MB mark. For comparation, with the script disabled mpv uses something like 99MB that doesn't increase at all over the time.

I can provide more data if you want, but I noticed this issue with my machine that only has 2GB of RAM.

**Comment by torque** [comment]
I expect that what looks like a memory leak is actually due to libass caching the various lines generated by the OSD. Unfortunately, there's nothing I can do about this, as mpv doesn't provide any options to control libass's cache size. While actual memory leaks have been [found and fixed](https://github.com/libass/libass/issues/175) in libass, the fact that this seems to stop at the same size every time indicates to me that it is simply the glyph cache working as usual.

Lua itself is a garbage collected language, so it would be pretty difficult for me to create a memory leak within this code. I'm going to close this since if there is an actual problem, I don't think it's in my code. If you have extra evidence that it looks like a genuine memory leak in mpv or libass, I can look further into it.
