### ISSUE TITLE
Update the link to the compiled script

### ISSUE THREAD

**Issue by sCreami** [torque/mpv-progressbar#2]
> [progressbar] 
[progressbar] stack traceback:
[progressbar] 	~/.config/mpv/scripts/progressbar.lua:1138: in function '__init'
[progressbar] 	~/.config/mpv/scripts/progressbar.lua:1188: in function <~/.config/mpv/scripts/progressbar.lua:1186>
[progressbar] 	\(...tail calls...)
[progressbar] 	mp.defaults:360: in function 'handler'
[progressbar] 	mp.defaults:436: in function 'call_event_handlers'
[progressbar] 	mp.defaults:472: in function 'dispatch_events'
[progressbar] 	mp.defaults:429: in function <mp.defaults:428>
[progressbar] 	[C]: in ?
[progressbar] 	[C]: in ?
[progressbar] Lua error: ~/.config/mpv/scripts/progressbar.lua:1138: attempt to call field 'get_screen_size' (a nil value)

Probably need to update the link to the compiled script.

**Comment by torque** [comment]
I haven't updated the compiled script because the Lua ODE API changes are new enough they aren't in a release yet, so I suspect most mpv users need the old version rather than the new one. I think I'll write a little shim around it so that both the new and old api versions can be simultaneously supported.

**Comment by torque** [comment]
Done.
