### ISSUE TITLE
showing system time in the upper right corner of filename line

### ISSUE THREAD

**Issue by tberger2** [torque/mpv-progressbar#21]
I don't like this peace of software.
I love it! :-)
It's so much better conceived than this built-in fossil of mpv...

There is a single thing I really could use:
Is is possible to additional show the system time in the upper right corner when hitting the request-display key?
Something like this:

FILENAME....................................................HH:MM

ELAPSED TIME.........BAR...........REMAINING TIME

Thanks alot!

**Comment by torque** [comment]
This would not be difficult to implement, but there's one small problem: because I have no real control over line layout in ASS (in particular, line width/margins), there are situations where it would overlap with the filename. This problem already manifests itself with low-resolution videos with long titles, though I guess that's not terribly common these days.

In short, sure. I'll try to get around to it by this weekend.

**Comment by torque** [comment]
Added in 16692604943a53721a7c47c4abc5af59780a76b1. Default is HH:MM (24 hour time). This just uses Lua builtins, so you should be able to use any `strftime`-compatible format string to change the output to your liking, using the new `system-time-format` option.

**Comment by tberger2** [comment]
Works perfectly, thank you very much!
