### ISSUE TITLE
Adjust the size of the pause indicator in conf file

### ISSUE THREAD

**Issue by sCreami** [torque/mpv-progressbar#24]
plz, my dpi is too high for this indicator for ants.

**Comment by torque** [comment]
Should be easy enough to do. I figured most people didn't use it.

**Comment by sCreami** [comment]
I thank you good Chap.

**Comment by torque** [comment]
I just got rid of this as it has been obsoleted by the setting `display-scale-factor` which scales the entire display for high-dpi screens. Now that I have a high-dpi screen myself, I deemed this to be a significantly better solution because it means most of the rest of the defaults will be fine if scaled.

**Comment by sCreami** [comment]
I think it’s a great idea. I used to have separate config files for my plebian display and my hdpi. Now, I can finally return to a single one.
