### ISSUE TITLE
Crash with chaptered files

### ISSUE THREAD

**Issue by robertgzr** [torque/mpv-progressbar#25]
I get this trying to play any matroska files containing chapters.

using:
* mpv git-ec74a79
* mpv-progressbar (master)

```
[progressbar]
[progressbar] stack traceback:
[progressbar]   [C]: in function 'format'
[progressbar]   $HOME/.config/mpv/scripts/progressbar.lua:972: in function '__init'
[progressbar]   $HOME/.config/mpv/scripts/progressbar.lua:989: in function 'ChapterMarker'
[progressbar]   $HOME/.config/mpv/scripts/progressbar.lua:1017: in function 'createMarkers'
[progressbar]   $HOME/.config/mpv/scripts/progressbar.lua:1682: in function 'handler'
[progressbar]   mp.defaults:448: in function 'call_event_handlers'
[progressbar]   mp.defaults:485: in function 'dispatch_events'
[progressbar]   mp.defaults:441: in function <mp.defaults:440>
[progressbar]   [C]: in ?
[progressbar]   [C]: in ?
[progressbar] Lua error: $HOME/.config/mpv/scripts/progressbar.lua:972: bad argument #1 to 'format' (not a number in proper range)
```

**Comment by torque** [comment]
This is interesting. Without testing, the chapters code is using the deprecated `length` property instead of `duration`, so I wonder if that has something to do with it. It's also possible that somehow the files are being loaded in such a way that the duration is unknown, though that shouldn't cause an exception. Will see if I can reproduce in a bit.

**Comment by torque** [comment]
Okay, finally got around to looking at this and as far as I can tell the problem is in fact division by zero caused by the deprecated `length` property having been removed at some point in the recent past. It doesn't crash for me, (on macOS using luajit 2.1), so I assume this is a platform or Lua runtime specific behavior. I'll commit this change but not mark it as fixed until you get back to me, since I'm not 100% sure this is the actual problem at hand.
