### ISSUE TITLE
No longer able to change colors/sizes

### ISSUE THREAD

**Issue by rikvidr** [torque/mpv-progressbar#31]
In the old osc.lua for this project, the option to change font color was ['foreground'] = ''

Now, it seems to be ['bar-foreground-style'] = '', in progressbar.lua, but putting any RGB hex in does not change it from this purple that I hate, whether I try it in progressbar.lua, or torque-progressbar.conf.

Then there's the matter of this gigantic font size, which I also can't seem to change, in either progressbar.lua, or torque-progressbar.conf.
https://aww.moe/9yd947.png

And then, the seek bar at the bottom has this gigantic grey thing surrounding it. https://aww.moe/wnt8x2.png

So, my question is, how do I change these? That purple is very difficult for me to read from across the room, I had my old settings as a lighter color, and that font wrapping isn't fun either. The grey thing moves with the progress bar, almost like an outer layer, and it's huge.

**Comment by torque** [comment]
Sorry I didn't leave instructions on how to migrate the config when I broke backwards compatibility—I'm not sure where to put them. Anyway, these config fields now take full ASS override tags because it allows significantly more customization.

To answer your questions directly:
To fix the huge font you probably need to set `display-scale-factor=1` in your config. This scales the entire script up for high-dpi displays, but it will cause it to look way too big on low-dpi displays. Unfortunately there does not appear to be an automatic solution, and mpv's high-dpi behavior may be platform-dependent anyway (I have only been able to check on macOS).

To change the color, you can change the config value
`default-style=\fnSource Sans Pro\b1\bord2\fs30\c&HFC799E&\3c&H2D2D2D&`. This sets the default font, weight, outline thickness, color, and outline color, in this order. Specifically, if you change the `\c&HFC799E&` part to `\c&HFF0000&` the main color will become completely blue. Likewise, the `\3c` part controls the color of the outline. The color format is BGR hexadecimal as before.

With regards the giant grey thing around the seek bar, that's an outline being drawn around it. To fix this, you should set `bar-default-style=\bord0` and make sure none of the other `bar*style` config settings have `bord` settings in them. Additionally, to change the bar foreground color, you should set e.g. `bar-foreground-style=\c&H0000FF&` to make the bar bright red (again, BGR hex, wrapped by an identifying tag).

If you care to do further research, a decent reference on ASS tags is [available here][tags]. mpv renders the OSC from ASS subtitles, which is why this is how it is styled.

[tags]: http://docs.aegisub.org/3.2/ASS_Tags/#override-tags

**Comment by rikvidr** [comment]
Thank you, that fixed all of my problems. I had never seen BGR hex before, so the \cH......& threw me way off. Thanks again, and I love this software, mpv's built-in OSC is hideous.
