### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by firewater2** [torque/mpv-progressbar#36]
1. What's this small black marker at the end? And how can I remove it, or recolor it so it looks like the rest of the bar?

![2017-04-29 22 26 39](https://cloud.githubusercontent.com/assets/11010067/25560459/0e7d34c0-2d23-11e7-85d6-7bbb8672b3d1.png)

2. Any quick way to modify the script so that the bar doesn't appear on mouse hover? My problem is that I have the cursor hidden on MPV so it doesn't makes sense for it to appear like that.

**Comment by onodera-punpun** [comment]
1. It is a dropshadow, I don't know how to remove it though.

2. Set https://github.com/torque/mpv-progressbar/blob/build/progressbar.lua#L63 to 0.

**Comment by torque** [comment]
Small corrections:

1. I agree it looks like a shadow. If you have all other elements disabled or you don't want shadow on them, you can add `\shad0` to the end of your [`default-style`](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf#L16) setting. Otherwise, if you want shadow on other elements, you should add `\shad0` to the [`bar-default-style`](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf#L56) setting. Actually, that should probably be in the defaults.

2. You should set both the [`hover-zone-height`](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf#L2) and [`top-hover-zone-height`](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf#L7) settings to 0.

If you don't already have a config file (though it looks like you probably do) there is information about what to name it and where to place it [in the readme](https://github.com/torque/mpv-progressbar#configuration) and more information about the configuration syntax/format [in mpv's documentation](https://mpv.io/manual/master/#configuration-files).

**Comment by firewater2** [comment]
Thanks guys, I believe it's fine now!

**Comment by firewater2** [comment]
Actually the shadow is still there, sorry. Now I know in which videos it appears for sure so I can test it properly. This would be my configuration file:

```
hover-zone-height=0
top-hover-zone-height=0
display-scale-factor=2
default-style=\fnHelvetica\b1\bord2\fs30\c&H0080F&\c&H2D2D2D&\

enable-bar=yes
hide-inactive=no
bar-height-inactive=0
bar-height-active=10
seek-precision=exact
bar-default-style=\bord0\shad0
bar-foreground-style=
bar-cache-style=\c&H0080F&
bar-background-style=\c&H101010&

enable-elapsed-time=no
elapsed-style=
elapsed-left-margin=4
elapsed-bottom-margin=0

enable-remaining-time=no
remaining-style=
remaining-right-margin=4
remaining-bottom-margin=0

enable-hover-time=no
hover-time-style=\fs26
hover-time-left-margin=120
hover-time-right-margin=130
hover-time-bottom-margin=0

enable-title=no
title-style=
title-left-margin=
4title-top-margin=0
title-print-to-cli=yes

enable-system-time=no
system-time-style=
system-time-format=%H:%M
system-time-right-margin=4
system-time-top-margin=0

pause-indicator=no
pause-indicator-foreground-style=\c&HFC799E&
pause-indicator-background-style=\c&H2D2D2D&

enable-chapter-markers=no
chapter-marker-width=2
chapter-marker-width-active=4
chapter-marker-active-height-fraction=1
chapter-marker-before-style=\c&HFC799E&
chapter-marker-after-style=\c&H2D2D2D&

request-display-duration=2
redraw-period=0.03
animation-duration=0.25

elapsed-offscreen-pos=-100
remaining-offscreen-pos=-100
system-time-offscreen-pos=-100
title-offscreen-pos=-40
```

**Comment by torque** [comment]
Let me ask for clarification: this only happens with certain videos?

Your config looks mostly ok, but you have a malformed color code in there twice:

`default-style=\fnHelvetica\b1\bord2\fs30\c&H0080F&\c&H2D2D2D&\`
`bar-cache-style=\c&H0080F&`

specifically, `\c&H0080F&` is missing a hex value (it has 5 instead of 6) this means the cache bar is probably rendering black instead of whatever color you were expecting (do note that the colors are specified as GGBBRR, rather than RRGGBB). This is also completely redundant in the `default-style` line, as it gets overridden by the `\c&H2D2D2D&` that immediately follows it. There's also a trailing `\`, but I don't think that should matter.

**Comment by torque** [comment]
I'm closing this issue under the assumption that it was resolved. Feel free to reopen it if you are still seeing this issue.

**Comment by firewater2** [comment]
I have no idea why i never answered you, sorry! It happened with only certain videos, I'm almost sure most of them were on the 'short' spectrum. Which I think was because the wrong color was the cache color being wrong, as you mention. I've fixed this with your instructions and everything seems to be working great now, thanks!

**Comment by jimmy-1000** [comment]
>...

In my case I have: **\shad0** and **hover-zone-height** in 0 and **top-hover-zone-heigh**t in 0 and I see the black square at the beginning of the progress bar. But like the previous member said, it happens in some videos but not others.
