### ISSUE TITLE
Crash when video is resumed

### ISSUE THREAD

**Issue by Argon-** [torque/mpv-progressbar#37]
Hi,
I'm using your progressbar as is from the built-branch, with some customization made only within the config.
When playing a video (must play for at least 1 sec) and then quitting (with `--save-position-on-quit`), opening the file again (and therefore resuming playback) will produce the following error:

    progressbar: stack traceback:
    progressbar: 	[C]: in function 'error'
    progressbar: 	/Users/Julian/.mpv/scripts/progressbar.lua:140: in function </Users/Julian/.mpv/scripts/progressbar.lua:138>
    progressbar: 	(tail call): ?
    progressbar: 	(tail call): ?
    progressbar: 	(tail call): ?
    progressbar: 	/Users/Julian/.mpv/scripts/progressbar.lua:661: in function 'update'
    progressbar: 	/Users/Julian/.mpv/scripts/progressbar.lua:500: in function 'animate'
    progressbar: 	/Users/Julian/.mpv/scripts/progressbar.lua:573: in function </Users/Julian/.mpv/scripts/progressbar.lua:565>
    progressbar: 	(tail call): ?
    progressbar: 	mp.defaults:320: in function 'process_timers'
    progressbar: 	mp.defaults:478: in function 'dispatch_events'
    progressbar: 	mp.defaults:451: in function <mp.defaults:450>
    progressbar: 	[C]: ?
    progressbar: 	[C]: ?
    progressbar: Lua error: /Users/Julian/.mpv/scripts/progressbar.lua:140: Trying to remove an element that doesn't exist in this stack.

Consequently, the progressbar is not shown.
Sample content of one offending saved state:

    start=4.185494
    pause=no

Removing `pause=no` from this file and using `--pause=no` on the command line when opening the file again does not lead to this crash. I have no idea what's going on.
This does also happen with my `torque-progressbar.conf` removed.

Any ideas or further information desired?

**Comment by torque** [comment]
This is weird. I almost exclusively use `quit-watch-later` because it's one of mpv's most useful features in my opinion, and I've never run into this bug. I still can't reproduce it now, even using `--save-position-on-quit`. You say this happens even if you remove `torque-progressbar.conf`?

The exception is happening in code I wrote, so a stopgap fix for you could be to change  [`progressbar.lua:140`](https://github.com/torque/mpv-progressbar/blob/build/progressbar.lua#L140) from `error("Trying to remove an element that doesn't exist in this stack.")` to `return`. However, this is treating the symptoms rather than the problem, and I'm interested in figuring out what's causing this.

It looks like you're on macOS. What version of mpv and lua are you using? In particular, my version doesn't write `pause=no` to the saved state (and when I tried adding it manually, it still didn't cause a problem). Also, can you post your mpv-progressbar configuration? You say that you can reproduce without it, but I wonder if having it will help me reproduce the problem. Do you remember when this started happening for you? I wonder if it was tied to an mpv update or to an update in mpv-progressbar itself.

Also, in the case that I can't manage to reproduce it, would you be willing to run a custom build to help me track down the problem?

**Comment by torque** [comment]
A neuron fired and I figured out how to reproduce it. By adding `pause=yes` to `mpv.conf` I encounter the same problem. I suspect that it's something buggy with the pause indicator's initial state, but I'll take a closer look as soon as I have time.

**Comment by Argon-** [comment]
Sorry, I just returned home. And yes indeed, I'm using `pause=yes` in my config. I should've mentioned that detail.
I'm using lua 5.2 and compiled mpv 6h ago. And of course I can test builds.

Unfortunately, I don't recall when it started. I'm also not a regular user of `save-position-on-quit` (well, until recently). It's actually happening for as long as I can remember, so at least a few months (only started using it this year).

**Comment by Argon-** [comment]
Thanks!
