### ISSUE TITLE
[FR] Yield settings (with description) into a separate file

### ISSUE THREAD

**Issue by Drugoy** [torque/mpv-progressbar#40]
I think it'd be a right thing to do to separate functional part from the config part.
Because config part is meant to be tuned by the user and it's hard to keep those changes when the script is updated, especially when you move the settings in the script's body.

**Comment by torque** [comment]
I'm not sure I understand the problem here. Are you editing `progressbar.lua` to change the settings?

If so, don't do that. The script settings are designed to use mpv's built in configuration system, which means that any setting you want to change you should put in the file `$MPV_HOME/lua-settings/torque-progressbar.conf`. If you're on Linux or macOS, `$MPV_HOME` is probably `~/.config/mpv` but it may also be `~/.mpv/`, where `~` is your home directory. On Windows, it is either the same directory as `mpv.exe` or `%appdata%\mpv`. Information on the config file syntax is included [in mpv's documentation](https://mpv.io/manual/master/#configuration-files) and mpv-progressbar's default configuration is [given in config-compatible syntax here](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf). Any lines that you don't change from the defaults can be deleted.

**Comment by Drugoy** [comment]
Ohwow. Yeah, I was modifying the .lua file, I didn't know it supported external confs by default. Thanks for educating me on that and sorry for wasting your time with this ticket!
