### ISSUE TITLE
Use ${demuxer-cache-state} property

### ISSUE THREAD

**Issue by haasn** [torque/mpv-progressbar#41]
https://github.com/mpv-player/mpv/commit/60df01512cf88d51b6334c95dab72de734f136fd

This exposes the demuxer state, including the seekable range, as a native mpv property. progressbar could use this instead of manually estimating this from the bitrate etc.

**Comment by haasn** [comment]
Ah, seems like this is not quite the same as mpv-progressbar's seekable range indication; since it's based only off the demuxer cache and not the network cache. It's only useful when using `--demuxer-seekable-cache` in a manner that has the demuxer cache replace the network cache.

**Comment by torque** [comment]
While you've pointed out this can't completely replace the current estimation method, I think it would improve the accuracy. Currently, I have to check the length of the demuxer cache anyway, but my understanding is that value includes some (unknown) amount of back cache, whereas `demuxer-cache-state` would give me actual timestamps. I'll give it a whirl.

**Comment by haasn** [comment]
The API for this changed upstream. Instead of just a single range, it now presents an entire list of seekable subregions (demuxer-cache-state/seekable-ranges).

The default OSC shows this as disjoint “cached” regions. Doing the same in progressbar would be really useful. (One thing that would need to be changed is adding the ability to highlight cached regions for already-played parts of the video file as well)

**Comment by FichteFoll** [comment]
+1 for highlighting played parts. Not that important, but it does help when you know you can seek to the past without having to rebuffer.

**Comment by torque** [comment]
This will require some re-thinking for the UI. Currently the bar itself is composed of 3 layers: the background, cache, and progress bar layers. Unless the user has set the `progress-bar-width` setting,  the bar covers any cache bar drawn prior to the point of current playback.

A quick idea is to draw the cached regions directly above the actual progress bar. This way cache in both directions would be visible. The problem with this is that screen real-estate is pretty valuable when the bar is inactive. I think that passively taking up 2 "pixels" at the bottom of the window is acceptable, but I'm not sure I want to take more than that.

With the the demuxer cache potentially creating disjoint ranges, it becomes non-obvious how to factor in the `cache-used` property, unless the new property automatically incorporates this (doubtful, because in general there's no actual way to know the length of a cached section until it has been demuxed). I primarily use mpv for watching youtube videos, and it's quite useful  to know how far I can seek without requiring stalling for network. I suppose I could probably remove the general cache and make my demuxer cache longer, if that works, though I'd prefer a more general solution, if possible.

**Comment by haasn** [comment]
> Unless the user has set the progress-bar-width setting, the bar covers any cache bar drawn prior to the point of current playback.

The obvious solution to me would be to move the cache layer to the top of the z-order. So basically, you'd have the background layer, then the progress bar layer on top of that, and then the (translucent) cache layer on top of that.

> With the the demuxer cache potentially creating disjoint ranges, it becomes non-obvious how to factor in the cache-used property, unless the new property automatically incorporates this

The cache-used property has not changed. So you can continue incorporating it in the exact same way as you currently do. They can be seen as orthogonal. I think the easiest thing to do would be to have a setting for each; so users who want to use the demuxer or stream cache exclusively can disable drawing the one they're not interested in.

Personally, I only use the demuxer cache. It's strictly better than the stream cache (allows estimating seekable ranges accurately, allows faster seeking, allows caching disjoint regions, etc.).

**Comment by torque** [comment]
I will implement this within the next week. As for `moonc`, I believe the expected way to install it is through `luarocks`, a lua package manager, which should have a package in most distros.

**Comment by torque** [comment]
I've changed the cache display implementation to use `demuxer-cache-state` exclusively. The most recent [build](https://github.com/torque/mpv-progressbar/blob/build/progressbar.lua) incorporates these changes. I didn't really settle on a visual appearance I was particularly happy with, but several new options have been added that hopefully run the gamut of configurability.

As a quick overview, the new settings are:

- `bar-cache-position=overlay` This can be 'overlay' or 'underlay' and controls whether the cache display is drawn on top of the progress bar or underneath it.
- `bar-cache-height-inactive=1.5` This controls the cache display bar height when not hovered or otherwise activated. 
- `bar-cache-height-active=4` This controls the cache display bar height when hovered or otherwise activated. 
-  `bar-background-adaptive=yes` This controls whether or not the background layer of the bar will try to always cover both the progress and cache displays, by being as tall as the max height of the other two.

These settings along with the existing `bar-*-style` offer quite a lot of permutations for stacking and displaying the bars.

**Comment by haasn** [comment]
Great, I like it already - at least with the customization options given I can mostly make it like I want.

One thing I don't quite like however: Is it possible that the bar cache overlay could use a different blending mode, like a "lighten" mode? Or alternatively, can I choose a different style for the regions where the cache bar intersects the non-cache bar?

I want the cached region to always appear slightly lighter than the rest, but if I put something like a light gray for the cache bar color, when overlaid onto purple it doesn't have the right effect.

**Comment by torque** [comment]
Yeah, I expected the overlapping areas to not work well with transparency. Unfortunately, ASS does not support different blending modes, so the only way to do this is to actually split the cache into two separate lines on the edge of the current progress. This is likely susceptible to subpixel (or more) rendering artifacts right at the border, though I doubt  it would be particularly visible. I'll take a look to see if splitting it is simple enough and doesn't result in too many composition issues.

**Comment by torque** [comment]
Ok, a new build is up, with a new option, `bar-cache-background-style`, that is applied to cache seek ranges after the current playback position (it is applied after the `bar-cache-style` setting). The implementation ended up relying on some of the wackier aspects of the way ASS handles drawing arbitrary shapes, so let me know if you see any strange behavior with it (namely it drawing the ranges in the wrong place), though I'm pretty sure I got it all ironed out.

**Comment by haasn** [comment]
@torque Thanks, now I can sort of approximate the effect I want. It's not 100% perfect, because I can't change the bar color while keeping the alpha value the same by just overlaying a different transparent region, but it's close enough to where I can leave it like this.

```
default-style=\fnSource Sans Pro\b1\bord2\fs30\alpha&H33&\c&HFC799E&\3c&H1A1A1A&
bar-default-style=\bord0
bar-foreground-style=
bar-cache-style=\alpha&BBE&\c&HFFFFFF&
bar-cache-background-style=\alpha&HBB&\c&HCCCCCC&
bar-background-style=\alpha&HBB&\c&H000000&

chapter-marker-width=2
chapter-marker-width-active=4
chapter-marker-active-height-fraction=1
chapter-marker-before-style=\c&HFC799E&
chapter-marker-after-style=\c&H1A1A1A&

bar-height-inactive=0
bar-height-active=20
bar-cache-height-inactive=0
bar-cache-height-active=20
bar-cache-position=overlay
```

**Comment by FichteFoll** [comment]
Just tried it out and am loving this. Also kudos for configurability.
