### ISSUE TITLE
Styling the pause/play icon

### ISSUE THREAD

**Issue by firewater2** [torque/mpv-progressbar#45]
I just realized this feature exists, and I like it so much I couldn't go back to not having it. It's just a little detail, but it makes a whole lot of a difference to me. Thanks for that.

Any way, I'm wondering how can I style it - particularly, how can I do so without having it adopt settings from the OSD? As it is, it inherits stuff like `osd-back-color`, making it pretty much corrupted and extremely unappealing. I believe I pretty much want it as it is by default, and maybe change the colors of the background (maybe to a complete transparent one), so this inherit thing isn't working for me.

Perhaps there could be a setting that disabled inheriting for all elements of this script?

**Comment by torque** [comment]
I don't believe I can do anything about inheriting the configured OSD style, since that's built-in mpv behavior. However, the settings `pause-indicator-background-style` and `pause-indicator-foreground-style` are provided to let you style the pause indicator (two settings because it's composed of two layers. The circle is the background and the icon itself is the foreground). These settings should allow you to override whatever your default OSD settings you don't like are. Like the other style configuration options, they're ASS override tags. If you're not familiar, some commonly useful tags are listed in [the reference configuration file](https://github.com/torque/mpv-progressbar/blob/master/torque-progressbar.conf#L16-L37).
