### ISSUE TITLE
Title not changing for new file in playlist

### ISSUE THREAD

**Issue by rezow** [torque/mpv-progressbar#50]
I'm using [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) script with mpv-progressbar and sometimes when a file is done playing and the next one in the playlist starts, the title won't update to the new file's title in the progress bar. This also happens when skipping to the next or previous file in the playlist. It doesn't happen every time and when it does, I've noticed that if I seek to a new point in the video with either the mouse or arrow key, then the title will update. I assume this is an issue with mpv-progressbar though it could belong to the autoload.lua script.

**Comment by torque** [comment]
I've noticed this issue too, so it's definitely a problem in mpv-progressbar, since I don't use `autoload.lua`. The issue (as far as I have tracked it down) is that mpv occasionally does not properly run the callback I have associated with a new file launching. This appears to be completely random, so I'm guessing it may actually be some timing issue, as the script actually currently juggles two different events (`file-loaded` and `playback-restart`) to handle initialization—though, looking at the commit log, I'm not actually sure why. A timing issue would be consistent with your observation that seeking fixes it, since seeking emits the `playback-restart` event.

I'll see if this can be fixed by using the `file-loaded` event only.

**Comment by torque** [comment]
Pushed a potential fix to the tip of the [build][build] branch, since the change was trivial. Obviously, testing it is not trivial since the misbehavior occurs at random, but I'd appreciate it if you could update and let me know if you still experience the issue after using it for some time.

[build]: https://github.com/torque/mpv-progressbar/tree/build

**Comment by rezow** [comment]
I've tested the new build and it works perfectly! Thanks for fixing that.

There is only one more issue I've noticed. Again, I'm not sure whether it belongs to `mpv-progressbar` or `autoload.lua`. When I play a file with a large amount of other files in the same directory, the queue numbers next to the title will be incorrect. E.g., if I play file 7/50 in the directory, mpv has 1/3 - "Title" displayed. This happens when somewhere around 40 files or more are added to the playlist (using `autoload.lua`).

Once a different file in the playlist starts playing, the queue updates and displays the correct numbers. So the issue I've described only happens for the first file being played.

**Comment by torque** [comment]
Based on your description, that sounds like a bad interaction between `autoload.lua` and `mpv-progressbar`. The title information (including the current video index and total playlist count) is gotten directly from mpv itself. It looks like `autoload.lua` hooks the `start-file` event, which probably means it doesn't finish populating the playlist information until after `mpv-progressbar` has done its initial UI drawing.

I suspect this is my fault, since the title/playlist display is only updated when a new video is loaded. I should probably instead observe the `playlist` property and automatically update when it is changed.

**Comment by torque** [comment]
I just pushed a fix and a new build that addresses this issue. I tested the fix with `umpv` and it seemed to work, so I think it probably also should be fixed for `autoload.lua` as well.

**Comment by rezow** [comment]
I tried out the new build with `autoload.lua` and everything works!

**Comment by FichteFoll** [comment]
Can confirm this also properly updates the "title" when appending more files (or URLs) to the playlist during playback (using `appendURL.lua`).

**Comment by rezow** [comment]
@torque could you contact me at rezowx AT outlook.com
